config/routes.rb
Agitosemana::Application.routes.draw do
  get "pedidos/index"

  match 'salvar-notificacao' => "notificacoes#salvar", :via => :post

  get "galerias/index"

  get "pagamento/retorno"

  match 'dados-cliente' => 'carrinho#dados_cliente', :as => :dados_cliente
  match 'carrinho' => 'carrinho#index', :as => :carrinho
  match 'carrinho/:produto_id' => 'carrinho#adicionar', :as => :adicionar_carrinho
  match 'carrinho/:produto_id/diminuir' => 'carrinho#diminuir', :as => :diminuir_carrinho
  match 'carrinho/:produto_id/remover' => 'carrinho#remover', :as => :remover_carrinho
  match 'efetuar_pagamento' => 'carrinho#efetuar_pagamento', :as => :efetuar_pagamento, :via => :post
  match 'finalizar' => 'finalizar#index', :as => :finalizar
  
  match 'produtos' => 'produtos#index', :as => :produtos
  match 'produto/:id' => 'produtos#detalhes', :as => :produto

  match 'fale-conosco' => 'fale_conosco#index', :as => :fale_conosco
  match 'enviar-fale-conosco' => 'fale_conosco#enviar_contato', :as => :enviar_contato, :via => :post

  match 'institucional/:pagina_url' => 'paginas#index', :as => :pagina
	match 'galeria/:id' => 'galerias#index', :as => :galeria
  
  

  namespace :admin do
    root :to => "produtos#index"
    
    match 'login/index'               => 'login#index',   :as => :login
    match 'login/logout'              => 'login#logout',  :as => :logout
    match 'login/enter'               => 'login#enter',   :as => :login_enter, :via => :post
    

    resources :pedidos

    resources :parametros    
    resources :produtos do
      resources :imagem_produtos
    end
    resources :categorias
    resources :banners    
    resources :usuarios
    resources :paginas
    resources :galerias do
      resources :imagem_galerias
    end
    
    
  end
  

  root :to => 'home#index'
end

app/models/banner.rb
class Banner < ActiveRecord::Base
  validates :descricao, :presence => true
	has_attached_file :imagem, :styles => { 
    :medium => "940x258!", 
    :thumb => "75x75#"},
  :default_style => :medium
  validates_attachment_presence :imagem
  
end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
  alias_attribute :name, :nome
  validates :nome, :presence => true
end

app/models/galeria.rb
class Galeria < ActiveRecord::Base
  has_many :imagem_galerias
  accepts_nested_attributes_for :imagem_galerias

  validates :nome, :presence => true
  validates :conteudo, :presence => true

  def capa
    self.imagem_galerias.first.img_galeria if self.imagem_galerias.count > 0
  end
end

app/models/imagem_galeria.rb
class ImagemGaleria < ActiveRecord::Base
  belongs_to :galeria

  has_attached_file :img_galeria, :styles => { 
    :normal => "260x260#", 
    :medium => "179x201#",
    :large => "400", 
    :thumb => "75x75#"}
    
  validates_attachment_presence :img_galeria
end

app/models/imagem_produto.rb
class ImagemProduto < ActiveRecord::Base
  belongs_to :produto
  has_attached_file :arquivo, :styles => { 
    :large => "260x260", 
    :medium => "179x201",
    :thumb => "75x75#"}
    
  validates_attachment_presence :arquivo
end

app/models/pagina.rb
class Pagina < ActiveRecord::Base
	validates :titulo, :presence => true, :uniqueness => true
	validates :conteudo, :presence => true
	
	before_save :set_url
	
	def set_url
		self.url = self.titulo.parameterize
		true
	end
end

app/models/parametro.rb
class Parametro < ActiveRecord::Base
  usar_como_dinheiro :taxa_embalagem

  validates_presence_of :taxa_embalagem

  def self.first_or_create
    self.first || self.new(:taxa_embalagem => 12)
  end
end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
	validates_presence_of :nome, :email, :cpf, :data_nascimento, :sexo, :telefone_1, :cep, :endereco, :numero, :bairro, :cidade, :estado,
  :entrega_cep, :entrega_endereco, :entrega_numero, :entrega_bairro, :entrega_cidade, :entrega_estado
  validates_presence_of :nome_fantasia, :razao_social, :cnpj, :telefone_empresa, :if => :pedido_para_empresa?


  def pedido_para_empresa?
    self.tipo_cliente == 1
  end
end

app/models/produto.rb
class Produto < ActiveRecord::Base
  scope :recentes, order('created_at DESC')
  scope :antigos, order('created_at ASC')
  scope :ativos, where(:ativo => true)
  scope :destaques, where(:destaque_inicial => true)
  validates :nome, :presence => true
  validates :categoria_id, :presence => true
  validates :valor, :presence => true
  validates :descricao, :presence => true
  validates :peso, :presence => true
  usar_como_dinheiro :valor, :valor_promocional
  belongs_to :categoria
  has_many :imagem_produtos, :class_name => "ImagemProduto"  
  has_attached_file :capa, :styles => { 
    :medium => "179x201",
    :large => "260x260", 
    :thumb => "75x75#",
    :mini => '45x45#'}
    
  validates_attachment_presence :capa
  
  accepts_nested_attributes_for :imagem_produtos
  
  def valor_ou_promocao
    self.valor_promocional.to_f <= 0 ? self.valor : self.valor_promocional
  end

  def to_param
    [id,nome].compact.join('-').parameterize
  end
  
end

app/models/tiny_print.rb
class TinyPrint < ActiveRecord::Base
  
  has_attached_file :image,
    :convert_options => { :quality =>  4 },
    :styles => { :small_thumb => [ "50x50", :jpg ],
	               :medium_thumb => [ "100x100", :jpg ],
                 :large_thumb => [ "370x370", :jpg ],
	               :detail_preview => [ "450x338", :jpg ] },
    #:path => "/prints/:id/:style.:extension",
    :default_url => "/images/missing/prints/:style.png"

end

app/models/tiny_video.rb
class TinyVideo < ActiveRecord::Base
  
  has_attached_file :original
  #, :path => "videos/:original/:id.:extension",

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
end

app/controllers/admin/pedidos_controller.rb
class Admin::PedidosController < Admin::AdminController
  def index
  	@pedidos = Pedido.where('pagseguro_id IS NOT NULL').all
  end

  def show
    @pedido = Pedido.find(params[:id])
    render :layout => 'admin/simples'
  end

end

app/helpers/admin/pedidos_helper.rb
module Admin::PedidosHelper
end

app/helpers/carrinho_helper.rb
module CarrinhoHelper
  def sub_total_compra
    carrinho_usuario.sum{|t| t[:valor] * t[:qtd]}
  end

  def taxa_embalagem
    carrinho_usuario.sum{|t| t[:qtd] * Parametro.first_or_create.taxa_embalagem}
  end

  def total_compra
    sub_total_compra + taxa_embalagem
  end

end

app/helpers/franquia_helper.rb
module FranquiaHelper
end

app/helpers/galeria_helper.rb
module GaleriaHelper
end

app/helpers/galerias_helper.rb
module GaleriasHelper
end

app/helpers/geracao_helper.rb
module GeracaoHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/missao_helper.rb
module MissaoHelper
end

app/helpers/museu_helper.rb
module MuseuHelper
end

app/helpers/paginas_helper.rb
module PaginasHelper
end

app/views/admin/pedidos/index.html.erb
<%
title 'Central de Vendas'
breadcrumbs([
  {:text => 'Central de Vendas'}
])
%>

<article class="module width_full">
  <header>
    <h3>Lista de pedidos</h3>
    
  </header>
  

  <table class="tablesorter" cellspacing="0"> 
    <thead> 
      <tr> 
        <!-- <th class="header"></th>  -->
        <th class="header">Identificação do cliente</th> 
        <th class="header">Código no pagseguro</th> 
        <th class="header">Código interno</th>
        <th class="header">Data da última atualização</th>
        <th class="header"></th>
      </tr> 
    </thead> 
    <tbody> 
      <% @pedidos.each do |pedido| %>
      <tr> 
        <!-- <td><input type="checkbox"></td>  -->
        <td>
        	<%= pedido.nome %>
        </td> 
        <td><%= pedido.pagseguro_id %></td> 
        <td>#<%= pedido.id %> - <%= pedido.status %></td>
        <td><%= l pedido.updated_at, :format => :long %></td>
        <td><%= link_to 'Mais informações', admin_pedido_path(pedido), :target => "_blank" %></td>
      </tr> 
      <% end %>

    </tbody> 
  </table>
  
</article>

app/views/admin/pedidos/show.html.erb
<table border="1" cellspacing="0" width="100%" cellpadding="2">
<tr>
  <th colspan="4">Pedido: #<%= @pedido.id %> - <%= @pedido.status %></th>
</tr>
<% if @pedido.pedido_para_empresa? %>
<tr>
  <th colspan="4">Dados da empresa</th>
</tr>
<tr>
  <td width="20%" align="right">Nome fatansia</td>
  <td width="30%"><%= @pedido.nome_fantasia %></td>
  <td width="20%" align="right">Razão Social</td>
  <td width="30%"><%= @pedido.razao_social %></td>
</tr>
<tr>
  <td align="right">Inscrição Estadual</td>
  <td><%= @pedido.inscricao_estadual %></td>
  <td align="right">CNPJ</td>
  <td><%= @pedido.cnpj %></td>
</tr>

<tr>
  <td align="right">Telefone</td>
  <td><%= @pedido.telefone_empresa %></td>
  <td align="right">Site</td>
  <td><%= @pedido.site %></td>
</tr>

<tr>
  <td align="right">Ramo atividade</td>
  <td colspan="3"><%= @pedido.ramo_atividade %></td>
</tr>
<% end -%>
<tr>
  <th colspan="4">Dados do comprador</th>
</tr>
<tr>
  <td width="20%" align="right">Nome</td>
  <td width="30%"><%= @pedido.nome %></td>
  <td width="20%" align="right">E-mail</td>
  <td width="30%"><%= @pedido.email %></td>
</tr>
<tr>
  <td align="right">Profissão</td>
  <td><%= @pedido.profissao %></td>
  <td align="right">CPF</td>
  <td><%= @pedido.cpf %></td>
</tr>

<tr>
  <td align="right">Telefone 1</td>
  <td><%= @pedido.telefone_1 %></td>
  <td align="right">Telefone 2</td>
  <td><%= @pedido.telefone_2 %></td>
</tr>

<tr>
  <td align="right">Celular</td>
  <td><%= @pedido.celular %></td>
  <td align="right">Data de nascimento</td>
  <td><%= @pedido.data_nascimento.strftime("%d/%m/%Y") %></td>
</tr>

<tr>
  <td align="right">Sexo</td>
  <td colspan="3"><%= @pedido.sexo %></td>
</tr>

<tr>
  <th colspan="4">Endereço</th>
</tr>

<tr>
  <td align="right">CEP</td>
  <td><%= @pedido.cep %></td>
  <td align="right">Endereço</td>
  <td><%= @pedido.endereco %></td>
</tr>

<tr>
  <td align="right">Número</td>
  <td><%= @pedido.numero %></td>
  <td align="right">Complemento</td>
  <td><%= @pedido.complemento %></td>
</tr>

<tr>
  <td align="right">Bairro</td>
  <td><%= @pedido.bairro %></td>
  <td align="right">Cidade</td>
  <td><%= @pedido.cidade %></td>
</tr>

<tr>
  <td align="right">Estado</td>
  <td colspan="3"><%= @pedido.estado %></td>
</tr>

<tr>
  <th colspan="4">Endereço de entrega</th>
</tr>

<tr>
  <td align="right">CEP</td>
  <td><%= @pedido.entrega_cep %></td>
  <td align="right">Endereço</td>
  <td><%= @pedido.entrega_endereco %></td>
</tr>

<tr>
  <td align="right">Número</td>
  <td><%= @pedido.entrega_numero %></td>
  <td align="right">Complemento</td>
  <td><%= @pedido.entrega_complemento %></td>
</tr>

<tr>
  <td align="right">Bairro</td>
  <td><%= @pedido.entrega_bairro %></td>
  <td align="right">Cidade</td>
  <td><%= @pedido.entrega_cidade %></td>
</tr>

<tr>
  <td align="right">Estado</td>
  <td colspan="3"><%= @pedido.entrega_estado %></td>
</tr>

<tr>
  <th colspan="4">Informações do pedido</th>
</tr>
<tr>
  <td align="right">Identificador no pagseguro</td>
  <td><strong><%= @pedido.pagseguro_id %></strong></td>
  <td align="right">Total</td>
  <td><strong><%= @pedido.total.real_contabil %></strong></td>
</tr>
<tr>
  <td align="right">Situação</td>
  <td colspan="3"><strong><%= @pedido.status %></strong></td>
</tr>
</table>

<a href="javascript:window.print()">Imprimir</a>