config/routes.rb
Agitosemana::Application.routes.draw do
  get "pedidos/index"

  match 'salvar-notificacao' => "notificacoes#salvar", :via => :post

  get "galerias/index"

  get "pagamento/retorno"

  match 'dados-cliente' => 'carrinho#dados_cliente', :as => :dados_cliente
  match 'carrinho' => 'carrinho#index', :as => :carrinho
  match 'carrinho/:produto_id' => 'carrinho#adicionar', :as => :adicionar_carrinho
  match 'carrinho/:produto_id/diminuir' => 'carrinho#diminuir', :as => :diminuir_carrinho
  match 'carrinho/:produto_id/remover' => 'carrinho#remover', :as => :remover_carrinho
  match 'efetuar_pagamento' => 'carrinho#efetuar_pagamento', :as => :efetuar_pagamento, :via => :post
  match 'finalizar' => 'finalizar#index', :as => :finalizar
  
  match 'produtos' => 'produtos#index', :as => :produtos
  match 'produto/:id' => 'produtos#detalhes', :as => :produto

  match 'fale-conosco' => 'fale_conosco#index', :as => :fale_conosco
  match 'enviar-fale-conosco' => 'fale_conosco#enviar_contato', :as => :enviar_contato, :via => :post

  match 'institucional/:pagina_url' => 'paginas#index', :as => :pagina
	match 'galeria/:id' => 'galerias#index', :as => :galeria
  
  

  namespace :admin do
    root :to => "produtos#index"
    
    match 'login/index'               => 'login#index',   :as => :login
    match 'login/logout'              => 'login#logout',  :as => :logout
    match 'login/enter'               => 'login#enter',   :as => :login_enter, :via => :post
    

    resources :pedidos

    resources :parametros    
    resources :produtos do
      resources :imagem_produtos
    end
    resources :categorias
    resources :banners    
    resources :usuarios
    resources :paginas
    resources :galerias do
      resources :imagem_galerias
    end
    
    
  end
  

  root :to => 'home#index'
end

app/models/produto.rb
class Produto < ActiveRecord::Base
  scope :recentes, order('created_at DESC')
  scope :antigos, order('created_at ASC')
  scope :ativos, where(:ativo => true)
  scope :destaques, where(:destaque_inicial => true)
  validates :nome, :presence => true
  validates :categoria_id, :presence => true
  validates :valor, :presence => true
  validates :descricao, :presence => true
  validates :peso, :presence => true
  usar_como_dinheiro :valor, :valor_promocional
  belongs_to :categoria
  has_many :imagem_produtos, :class_name => "ImagemProduto"  
  has_attached_file :capa, :styles => { 
    :medium => "179x201",
    :large => "260x260", 
    :thumb => "75x75#",
    :mini => '45x45#'}
    
  validates_attachment_presence :capa
  
  accepts_nested_attributes_for :imagem_produtos
  
  def valor_ou_promocao
    self.valor_promocional.to_f <= 0 ? self.valor : self.valor_promocional
  end

  def to_param
    [id,nome].compact.join('-').parameterize
  end
  
end

app/controllers/admin/produtos_controller.rb
class Admin::ProdutosController < Admin::AdminController
  uses_tiny_mce(:options => AppConfig.default_mce_options, :only => [:new, :edit])
  
  # GET /admin/produtos
  # GET /admin/produtos.xml
  def index
    @admin_produtos = Produto.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @admin_produtos }
    end
  end

  # GET /admin/produtos/1
  # GET /admin/produtos/1.xml
  def show
    @admin_produto = Produto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @admin_produto }
    end
  end

  # GET /admin/produtos/new
  # GET /admin/produtos/new.xml
  def new
    @admin_produto = Produto.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @admin_produto }
    end
  end

  # GET /admin/produtos/1/edit
  def edit
    @admin_produto = Produto.find(params[:id])
  end

  # POST /admin/produtos
  # POST /admin/produtos.xml
  def create
    @admin_produto = Produto.new(params[:produto])

    respond_to do |format|
      if @admin_produto.save
        # sleep 1
        format.html { redirect_to(admin_produtos_path, :notice => 'Produto foi criado(a) corretamente.') }
        format.xml  { render :xml => @admin_produto, :status => :created, :location => @admin_produto }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @admin_produto.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/produtos/1
  # PUT /admin/produtos/1.xml
  def update
    @admin_produto = Produto.find(params[:id])

    respond_to do |format|
      if @admin_produto.update_attributes(params[:produto])
        # sleep 1
        format.html { redirect_to(admin_produtos_path, :notice => 'Produto foi atualizado(a) corretamente.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @admin_produto.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/produtos/1
  # DELETE /admin/produtos/1.xml
  def destroy
    @admin_produto = Produto.find(params[:id])
    @admin_produto.destroy

    respond_to do |format|
      # sleep 1
      format.html { redirect_to(admin_produtos_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  def index
    @produtos = []
    unless params[:q].blank?
      @produtos = Produto.ativos.recentes.where('nome LIKE ? OR descricao LIKE ?',"%#{params[:q]}%","%#{params[:q]}%")
    else
      @produtos = Produto.ativos.recentes
    end
  end

  def detalhes
    @produto = Produto.find(params[:id])
  end

end

app/helpers/admin/produtos_helper.rb
module Admin::ProdutosHelper
  
  
  def imagem_produto(produto_id,definicao = :mini)
    image_tag(Produto.find(produto_id).capa.url(definicao)) rescue ''
  end
  
  def preco_produto(preco)
    preco.to_f.real_contabil
  end
  
  def link_to_add_fields(name, f, association, link_options = {})
    link_options = {:class => "add_fields"}.merge(link_options)
    new_object = f.object.send(association).new
    logger.info { new_object.object_id.inspect }
    id = new_object.object_id
    fields = f.fields_for(association, new_object, :child_index => id) do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    logger.info { "-----------" }
    logger.info { fields.inspect }
    link_to(name, '#', link_options.merge('data-id' => id, 'data-fields' => escape_javascript(fields)))
  end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/admin/produtos/_form.html.erb
<%= simple_form_for([:admin, @admin_produto], :html => {:multipart => true}) do |f| %>
<div class="module_content">
  <fieldset>
    <%= f.association :categoria %>
  </fieldset>
  <fieldset>
    <%= f.input :nome %>
  </fieldset>
  <fieldset>
    <%= f.input :codigo_interno %>
  </fieldset>
  <fieldset>
    <%= f.label :descricao %>
  </fieldset>
  <%= f.text_area :descricao, :rows => 15, :cols => '100%', :class => 'mceEditor' %>
  <fieldset>
    <%= f.input :video %>
  </fieldset>
  <fieldset>
    <%= f.input :capa %>
  </fieldset>
  <% unless @admin_produto.new_record? -%>
    <%= image_tag @admin_produto.capa.url(:thumb) %>
  <% end -%>
  <fieldset>
    <%= f.input :valor, :input_html => {:type => :text, :value => f.object.valor.to_f.real_contabil} %>
  </fieldset>
  <fieldset>
    <%= f.input :valor_promocional, :input_html => {:type => :text, :value => f.object.valor_promocional.to_f.real_contabil} %>
  </fieldset>
  <fieldset>
    <%= f.input :peso, :input_html => {:type => :text, :value => f.object.peso.to_f} %>
  </fieldset>
  <fieldset>
    <%= f.input :ativo %>
  </fieldset>
  <fieldset>
    <%= f.input :destaque_inicial %>
  </fieldset>
  
  <h2>Imagens</h2>
  <% @admin_produto.imagem_produtos.count.upto(@admin_produto.imagem_produtos.count+2) do %>
    <% @imagem_produto = ImagemProduto.new %>
    <%=f.fields_for :imagem_produtos, @imagem_produto, :child_index => @imagem_produto.object_id do |fi| %>
    <fieldset>
      <%=fi.input :arquivo %>
    </fieldset>
    <% end -%>
  <% end -%>
  
    <% unless @admin_produto.new_record? %>
    <% @admin_produto.imagem_produtos.each do |imagem_produto| %>
    <div style="float: left; text-align: center;padding:5px; margin:4px; border:1px solid #ccc">
      <%=image_tag imagem_produto.arquivo.url(:thumb)%><br />
      <%=link_to 'Remover', admin_produto_imagem_produto_path(@admin_produto,imagem_produto), :method => :delete, :confirm => 'Deseja remover?' %>
    </div>
    <% end -%>
    <% end %>
    <div style="clear: both"></div>
  
</div>
<footer>
  <div class="submit_link">
    <%= f.button :submit, :value => 'Salvar', :class => 'alt_btn' %>
  </div>
</footer>
<% end %>

app/views/admin/produtos/_imagem_produto_fields.html.erb
<dt>
  <%= f.label :arquivo %>
</dt>
<dd>
  <%= f.file_field :arquivo %>
  <% unless f.object.new_record? %>
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remover" %>
  <% end %>
</dd>

app/views/admin/produtos/edit.html.erb
<%
title 'Produtos - Novo Produto'
breadcrumbs([
  {:text => 'Produtos', :url => admin_produtos_path},
  {:text => 'Alterando produto'},
])
%>
<article class="module width_full">
  <header><h3>Alterando produto</h3></header>
  <%= render 'form' %>
</article>

app/views/admin/produtos/index.html.erb
<%
title 'Lista de produtos'
breadcrumbs([
  {:text => 'Lista de produtos'}
])
%>

<article class="module width_full">
  <header>
    <h3>Lista de produtos </h3>
    
  </header>
  <%=button_new('Criar produto',new_admin_produto_path)%>
  

  <table class="tablesorter" cellspacing="0"> 
    <thead> 
      <tr> 
        <!-- <th class="header"></th>  -->
        <th class="header">Nome</th> 
        <th class="header">Categoria</th> 
        <th class="header">Valor</th>
        <th class="header">Ativo?</th>  
        <th class="header">Ações</th> 
      </tr> 
    </thead> 
    <tbody> 
      <% @admin_produtos.each do |admin_produto| %>
      <tr> 
        <!-- <td><input type="checkbox"></td>  -->
        <td><%= admin_produto.nome %></td> 
        <td><%= admin_produto.categoria.nome %></td> 
        <td><%= admin_produto.valor.real %></td>
        <td><%= admin_produto.ativo ? 'Sim' : 'Não' %></td> 
        <td><%= actions_common(admin_produto)%></td> 
      </tr> 
      <% end %>

    </tbody> 
  </table>
  
</article>

app/views/admin/produtos/new.html.erb
<%
title 'Produtos - Novo Produto'
breadcrumbs([
  {:text => 'Produtos', :url => admin_produtos_path},
  {:text => 'Novo produto'},
])
%>
<article class="module width_full">
  <header><h3>Novo produto</h3></header>
  <%= render 'form' %>
</article>

app/views/admin/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Categoria:</b>
  <%= @admin_produto.categoria %>
</p>

<p>
  <b>Nome:</b>
  <%= @admin_produto.nome %>
</p>

<p>
  <b>Codigo interno:</b>
  <%= @admin_produto.codigo_interno %>
</p>

<p>
  <b>Descricao:</b>
  <%= @admin_produto.descricao %>
</p>

<p>
  <b>Video:</b>
  <%= @admin_produto.video %>
</p>

<p>
  <b>Capa:</b>
  <%= @admin_produto.capa %>
</p>

<p>
  <b>Valor:</b>
  <%= @admin_produto.valor %>
</p>

<p>
  <b>Valor promocional:</b>
  <%= @admin_produto.valor_promocional %>
</p>

<p>
  <b>Ativo:</b>
  <%= @admin_produto.ativo %>
</p>

<p>
  <b>Destaque inicial:</b>
  <%= @admin_produto.destaque_inicial %>
</p>


<%= link_to 'Edit', edit_admin_produto_path(@admin_produto) %> |
<%= link_to 'Back', admin_produtos_path %>