config/routes.rb
Agitosemana::Application.routes.draw do
  get "pedidos/index"

  match 'salvar-notificacao' => "notificacoes#salvar", :via => :post

  get "galerias/index"

  get "pagamento/retorno"

  match 'dados-cliente' => 'carrinho#dados_cliente', :as => :dados_cliente
  match 'carrinho' => 'carrinho#index', :as => :carrinho
  match 'carrinho/:produto_id' => 'carrinho#adicionar', :as => :adicionar_carrinho
  match 'carrinho/:produto_id/diminuir' => 'carrinho#diminuir', :as => :diminuir_carrinho
  match 'carrinho/:produto_id/remover' => 'carrinho#remover', :as => :remover_carrinho
  match 'efetuar_pagamento' => 'carrinho#efetuar_pagamento', :as => :efetuar_pagamento, :via => :post
  match 'finalizar' => 'finalizar#index', :as => :finalizar
  
  match 'produtos' => 'produtos#index', :as => :produtos
  match 'produto/:id' => 'produtos#detalhes', :as => :produto

  match 'fale-conosco' => 'fale_conosco#index', :as => :fale_conosco
  match 'enviar-fale-conosco' => 'fale_conosco#enviar_contato', :as => :enviar_contato, :via => :post

  match 'institucional/:pagina_url' => 'paginas#index', :as => :pagina
	match 'galeria/:id' => 'galerias#index', :as => :galeria
  
  

  namespace :admin do
    root :to => "produtos#index"
    
    match 'login/index'               => 'login#index',   :as => :login
    match 'login/logout'              => 'login#logout',  :as => :logout
    match 'login/enter'               => 'login#enter',   :as => :login_enter, :via => :post
    

    resources :pedidos

    resources :parametros    
    resources :produtos do
      resources :imagem_produtos
    end
    resources :categorias
    resources :banners    
    resources :usuarios
    resources :paginas
    resources :galerias do
      resources :imagem_galerias
    end
    
    
  end
  

  root :to => 'home#index'
end

app/models/pagina.rb
class Pagina < ActiveRecord::Base
	validates :titulo, :presence => true, :uniqueness => true
	validates :conteudo, :presence => true
	
	before_save :set_url
	
	def set_url
		self.url = self.titulo.parameterize
		true
	end
end

app/controllers/admin/paginas_controller.rb
class Admin::PaginasController < Admin::AdminController
	uses_tiny_mce(:options => AppConfig.default_mce_options, :only => [:new, :edit])

  # GET /admin/paginas
  # GET /admin/paginas.xml
  def index
    @admin_paginas = Pagina.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @admin_paginas }
    end
  end

  # GET /admin/paginas/1
  # GET /admin/paginas/1.xml
  def show
    @admin_pagina = Pagina.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @admin_pagina }
    end
  end

  # GET /admin/paginas/new
  # GET /admin/paginas/new.xml
  def new
    @admin_pagina = Pagina.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @admin_pagina }
    end
  end

  # GET /admin/paginas/1/edit
  def edit
    @admin_pagina = Pagina.find(params[:id])
  end

  # POST /admin/paginas
  # POST /admin/paginas.xml
  def create
    @admin_pagina = Pagina.new(params[:pagina])

    respond_to do |format|
      if @admin_pagina.save
        # sleep 1
        format.html { redirect_to(@admin_pagina, :notice => 'Pagina foi criado(a) corretamente.') }
        format.xml  { render :xml => @admin_pagina, :status => :created, :location => @admin_pagina }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @admin_pagina.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/paginas/1
  # PUT /admin/paginas/1.xml
  def update
    @admin_pagina = Pagina.find(params[:id])

    respond_to do |format|
      if @admin_pagina.update_attributes(params[:pagina])
        # sleep 1
        format.html { redirect_to(admin_paginas_path, :notice => 'Pagina foi atualizado(a) corretamente.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @admin_pagina.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/paginas/1
  # DELETE /admin/paginas/1.xml
  def destroy
    @admin_pagina = Pagina.find(params[:id])
    @admin_pagina.destroy

    respond_to do |format|
      # sleep 1
      format.html { redirect_to(admin_paginas_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/paginas_controller.rb
class PaginasController < ApplicationController
  def index
  	@pagina = Pagina.find_by_url(params[:pagina_url])
  	raise unless @pagina
    @galerias = Galeria.all
  rescue
  	redirect_to root_path
  end

end

app/helpers/admin/paginas_helper.rb
module Admin::PaginasHelper
end

app/helpers/paginas_helper.rb
module PaginasHelper
end

app/views/admin/paginas/_form.html.erb
<%= simple_form_for([:admin,@admin_pagina]) do |f| %>
<div class="module_content">
  <fieldset>
    <%= f.input :titulo %>
  </fieldset>
  <fieldset>
  	<%= f.label :conteudo %>
  </fieldset>
  <%= f.text_area :conteudo, :rows => 15, :cols => '100%', :class => 'mceEditor' %>
</div>
<footer>
  <div class="submit_link">
    <%= f.button :submit, :value => 'Salvar', :class => 'alt_btn' %>
  </div>
</footer>
<% end %>

app/views/admin/paginas/edit.html.erb
<%
title 'páginas - Alterando página'
breadcrumbs([
  {:text => 'páginas', :url => admin_paginas_path},
  {:text => 'Alterando página'},
])
%>
<article class="module width_full">
  <header><h3>Alterando página</h3></header>
  <%= render 'form' %>
</article>

app/views/admin/paginas/index.html.erb
<%
title 'Lista de páginas'
breadcrumbs([
  {:text => 'Lista de páginas'}
])
%>

<article class="module width_full">
  <header>
    <h3>Lista de páginas </h3>    
  </header>
  

  <table class="tablesorter" cellspacing="0"> 
    <thead> 
      <tr> 
        <!-- <th class="header"></th>  -->
        <th class="header">Título</th> 
        <th class="header">Ações</th> 
      </tr> 
    </thead> 
    <tbody> 
      <% @admin_paginas.each do |admin_pagina| %>
      <tr> 
        <!-- <td><input type="checkbox"></td>  -->
        <td><%= admin_pagina.titulo %></td> 
        <td><%= action_edit(url_for(:action => :edit, :id => admin_pagina)) %></td> 
      </tr> 
      <% end %>

    </tbody> 
  </table>
  
</article>

app/views/admin/paginas/new.html.erb
<h1>New admin_pagina</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_paginas_path %>

app/views/admin/paginas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @admin_pagina.titulo %>
</p>

<p>
  <b>Conteudo:</b>
  <%= @admin_pagina.conteudo %>
</p>


<%= link_to 'Edit', edit_admin_pagina_path(@admin_pagina) %> |
<%= link_to 'Back', admin_paginas_path %>